version: "3.9"

services:
  app:
    image: edureport/app:latest
    build:
      context: .. # build from repo root
      dockerfile: deployment/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app # mount repo root into container
    # Example usage:
    # docker compose -f deployment/docker-compose.yml run --rm app php artisan reports:generate student1 1
    entrypoint: ""
    command: ["-v"]

  test:
    image: edureport/test:latest
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    entrypoint: ["bash", "-lc"]
    command: >
      "set -euo pipefail;
       composer install --no-interaction --prefer-dist;
       if [ ! -f .env ]; then
         if [ -f .env.testing ]; then cp .env.testing .env;
         elif [ -f .env.example ]; then cp .env.example .env;
         else touch .env; fi
       fi;
       php artisan key:generate --force;
       php artisan config:clear;
       vendor/bin/pest"
