version: "3.9"

services:
  app:
    image: edureport/app:latest
    build:
      context: .. # build from repo root
      dockerfile: deployment/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app # mount repo root into container
    # Example usage:
    # docker compose -f deployment/docker-compose.yml run --rm app php artisan reports:generate student1 1
    entrypoint: ""
    command: ["-v"]

  test:
    image: edureport/test:latest
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    entrypoint: ["bash", "-lc"]
    command: >
      "set -euo pipefail;
       vendor/bin/pest"

  composer:
    image: composer:2
    working_dir: /app
    volumes:
      - ..:/app
      - composer-cache:/tmp/composer-cache
    entrypoint: ["bash","-lc"]
    command: >
      'composer install --no-interaction --prefer-dist --no-ansi --no-progress'

volumes:
  composer-cache:
